spring:
  application:
    name: sharding-jdbc
  datasource:
    url: jdbc:shardingsphere:classpath:config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
# JPA Configuration
  jpa:  
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
# H2 Configuration
  h2: 
    console:      enabled: false
# DevTools Configuration
  devtools:
    add-properties: false     livereload:      enabled: true 